name: Build Image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Image
        uses: docker/build-push-action@v4
        with:
          context: ./emart-fresh-spring/demo
          file: ./emart-fresh-spring/demo/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/back-end:latest

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          timeout: 40s
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/back-end:latest
            docker rm -f fresh-backend
            docker run -d \
              -p 8080:8080 \
              -e DB_HOST=mydb \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
              -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
              -e BOOTPAY_ID=${{ secrets.BOOTPAY_ID }} \
              -e BOOTPAY_PRIVATE_KEY=${{ secrets.BOOTPAY_PRIVATE_KEY }} \
              -e JWT_TOKEN=${{ secrets.JWT_TOKEN }} \
              -e CD_CLOUDNAME=${{ secrets.CD_CLOUDNAME }} \
              -e CD_API_KEY=${{ secrets.CD_API_KEY }} \
              -e CD_API_SECRET=${{ secrets.CD_API_SECRET }} \
              --name fresh-backend \
              --link mydb:db \
              ${{ secrets.DOCKERHUB_USERNAME }}/back-end:latest
